# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://mysql3.cs.stonybrook.edu:3306/redwood?useSSL=false&zeroDateTimeBehavior=convertToNull
    username: HIDDEN
    password: HIDDEN

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: HIDDEN@gmail.com
    password: HIDDEN
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

